name: Bug Report
description: File a bug report
title: "[Bug]: (Enter short, one sentance summary of bug here)"
labels: ["bug"]
assignees:
  - ThioJoe
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        IS THIS A FEATURE REQUEST OR IDEA? SUBMIT A DISCUSSION POST INSTEAD HERE: https://github.com/ThioJoe/YouTube-Spammer-Purge/discussions
  - type: checkboxes
    id: no-issues-relating-to-this
    attributes:
      label: Duplicate Issues
      description: By submitting this issue, you are sure that there are no issues surronding this problem.
      options:
        - label: Are there are **no issues relating to your problem**
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I had a problem..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: What version of this program are you using? (can be found in the title when running (eg. ======== YOUTUBE SPAMMER PURGE VERSION (insert version here) or in the `version` variable in the `YouTubeSpammerPurge.py` file.)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: This will allow me to figure out where the issue originates.
      placeholder: Step 1, Step 2, Step 3...
      value: |
             1. 
             2. 
             3. 
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing this problem on?
      description: Sometimes, problems can be platform-specific.
      multiple: false
      options:
        - Windows
        - MacOS
        - Linux (can also be ChromeOS)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste from tracebacks
      render: shell
