name: Bug Report
description: File a bug report
title: "[Bug]: (Enter short, one sentance summary of bug here)"
labels: ["bug"]
assignees:
  - ThioJoe
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: no-issues-relating-to-this
    attributes:
      label: Duplicate Issues
      description: By submitting this issue, you are sure that there are no issues surronding this problem.
      options:
        - label: Are there are **no issues relating to your problem**
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "I had a problem..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste from tracebacks
      render: shell
